---
- hosts:
    - ziqqnode00
    - ziqqnode01
    - ziqqnode02

  tasks:
    - name: Configure firewall
      include_tasks:
        file: ./playbooks/infrastructure/uwf_configuration.yml
      when: confifgure_firewall == true

    - name: Install Docker in Homelab nodes
      include_tasks:
        file: ./playbooks/infrastructure/docker.yml
      when: install_docker == true

    # - name: Install K3S Server
    #   include_tasks:
    #     file: ./playbooks/infrastructure/k3s_server.yml
    #   when: ansible_hostname == 'ziqqnode00' and install_k3s_server==true

    - name: Install K3S Agent on Node01
      include_tasks:
        file: ./playbooks/infrastructure/k3s_agents.yml
      when: ansible_hostname == 'ziqqnode01'

    - name: Install K3S Agent on Node02
      include_tasks:
        file: ./playbooks/infrastructure/k3s_agents.yml
      when: ansible_hostname == 'ziqqnode02'
