---
  - name: Label agent nodes as worker nodes
    remote_user: ziqq
    become: true
    shell: |
      kubectl label nodes ziqqnode01 node-type=worker
      kubectl label nodes ziqqnode02 node-type=worker