---
  # Server token should be private and hidden behind Vault - for homelab simplicity I'm making it visible
  - name: Install K3S server instance for master node and extract token
    remote_user: ziqq
    become: true
    shell: |
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init" sh -
      mkdir -p $HOME/.kube
      sudo cp -i /etc/rancher/k3s/k3s.yaml $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
      echo "export KUBECONFIG=$HOME/.kube/config" >> $HOME/.bashrc
      source $HOME/.bashrc 
      sudo cat /var/lib/rancher/k3s/server/token
    